#!/usr/bin/env python3
"""
ModelServe — Feast Feature Materialization

Materializes features from the offline store (parquet file) to the
Redis online store so the FastAPI service can fetch them at inference time.

Prerequisites:
    - Redis must be running
    - feast apply must have been run in feast_repo/
    - training/features.parquet must exist (generated by feast_preprocess)

Usage:
    python scripts/materialize_features.py
"""

import sys
from datetime import datetime, timedelta
from pathlib import Path

# Ensure project root is on the path
project_root = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(project_root))

from feast import FeatureStore


def main():
    feast_repo_path = project_root / "feast_repo"
    print(f"Connecting to Feast repo at: {feast_repo_path}")

    store = FeatureStore(repo_path=str(feast_repo_path))

    # Materialize features up to now
    end_date = datetime.utcnow()
    start_date = end_date - timedelta(days=730)  # 2 years back

    print(f"Materializing features from {start_date} to {end_date}...")

    try:
        store.materialize(
            start_date=start_date,
            end_date=end_date,
        )
        print("Feature materialization complete!")
        print("Features are now available in the Redis online store.")
    except Exception as e:
        print(f"Materialization failed: {e}")
        print("\nTroubleshooting:")
        print("  1. Is Redis running? (docker compose up redis)")
        print("  2. Did you run 'cd feast_repo && feast apply'?")
        print("  3. Does training/features.parquet exist?")
        sys.exit(1)


if __name__ == "__main__":
    main()
