encryptionsalt: v1:H9GiZf8tRFI=:v1:ElajlSLAnGlYeANf:Jdb9sQq9FIF5RUWcovUpBdAiaXK6VA==
config:
  aws:region: ap-southeast-1
  modelserve-infra:publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCqAZfTPj6KQSUkjHoi3VSznvyb5rpIa9Ue5M5xQeV2729Pudzmgvya6a6VVhbderGVx9SZ6g4V2iwJk+Y9lX3kLRZSL8xML3wzSjlNKTQUVCEgGOr4nvRixTyDoHzRx8hBiiy0G7tz8h/XOG6YIJTmvmw36XUlyu+MYPrUAaw4LXf7m9jx+V/5oR3o3x7U4fNfTJ1Jda0B9dn/iF8e/ohUUiU5GbY5LRp4XGF0yivzvl6xAHV750633/1UF6ZPeRgaiid8+BvazZ5nmIDHm9YaNHoFOkrV7p/gyJf9Ft7PIe0VmV++H3Oz49OEFGkmmNeFGPv8dNrJ4ygLe3O3wskgDd9tsNTiYCDekmxglIeC72fF/1kPTBUsyV15IUW4XPNKwEPtzSZJqTAEHVDQq4Cgkn6h/5OVOP52MBqfAyrW5eqzXpsOaMoaJeS9eWhvuhADmePaAbqZ9m+UaEeH0zT4cW8Ln/05/Tylu+NyUZWwbjrgEGle9Rtd+W7P8bjVux6T8PR9InEKO5wh2g47ZW7hTGOldrHA52VycXuUUd7l0FfAJOUJjAz1BApLgBW6B5URuB1VPjMmnkSPpGF5qbW3z63r+O1WyflDmURPKYhDFtTuSZFL1oRXZSBUjqLDUVhNLByh28fXEC1+3RiiA2dqsZvIJzPg0zZDducpjBrVAQ== poridhian@6a0b0b390cf046f3
  modelserve-infra:awsAccessKeyId:
    secure: v1:hivJy5aaWf+as8wV:9nCpoG52fpr1Czjk3UFCw32+AHTy4yn1TTPc2YWpzSSiMc3D
  modelserve-infra:awsSecretAccessKey:
    secure: v1:baQh2JTeNlCKy3l6:SQaDljn0r92HjduJE4dcAjAKVLfEI2P4OZDoUEDxTsk0C+Wa/G0ly9FW9teVcLxQl5LqhD2Wu2Y=
  modelserve-infra:dockerHubUser: mahianol
  modelserve-infra:dockerImage: mahianol/modelserve-api:latest
