encryptionsalt: v1:H9GiZf8tRFI=:v1:ElajlSLAnGlYeANf:Jdb9sQq9FIF5RUWcovUpBdAiaXK6VA==
config:
  aws:region: ap-southeast-1
  modelserve-infra:publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQChWkOTNejET4YTHsa13xdp8zs3rGkjYs9UzAYc1t50TgWXTqU1vI2v4bOA7EHnvV60QA1KOpbAGXE1Mv+uh5cuHCXOC8y98KmkGlujLq4lG6SgrMVK5DvPfdkJXuW2PGxDxWsQ4w87xMTAZBqXti4ZWRQSIbBi4FaZ0NDQ68/cSp0kS7JDB6t7RNMUDp8jfkYyEtib+33imRU9+tIGftqX9g3BqCwkIgoLVDzsGdFlJUGzQQBDH2HfTbSodJhgdDVMT/ma+1pTEiO7XsnOtSHOXIww9aGzjAWUxDbw9cU7mmN9NCZqEuQ91esQj80zCnBFN9DpnrubRUgQFq3lBOiBeYK856/1tcEsyXp6wmFAktBbxX5UVtuwAcWVvJbVVg2V8aBLaERLXdm73cC5JTduUg4Kl48DeObp6s13RpvFFb20oNa+YRyfUfh+lV5oMygkak4Vnpwew9lce3xFdtYT0ObJtUZFS5ieINUHOaV4AG/aHKYAi2WQ3auVZpsKwSkURXmWzqGxNX0HtU6OnYfzN3g4CVIuFkAX4m4lz19TK62Yo4KKHasz3HpBfu2lvXtt/Zz6dTBk1wPMCE7SdyNlsA3cyPxybHJdkcWDDii+HVIKFNsl6sSZB2mZjq8Rh4bh8Q9a5IDCu7EN56PmUCS6/DqTb/kOaP92JQZFWKYY3w== poridhian@03c88464899349d0
  modelserve-infra:awsAccessKeyId:
    secure: v1:BH3pD6XOE54X2a1k:hVgA6GPnqv+eu6F3dyjUiHINUNnBCCg1XuOc+cn+yc7dRmmQ
  modelserve-infra:awsSecretAccessKey:
    secure: v1:qjD7LWwIJ/guYS4H:VlN9CJCV+u6PG4Ip9ZmWhJ/NLHNCfjBMqD5SsDcLBGb6Haa9SDHHo6UK2DwBL+kd9wprRyIvnms=
  modelserve-infra:dockerHubUser: mahianol
  modelserve-infra:dockerImage: mahianol/modelserve-api:latest
